### ISSUE TITLE
README.md should be converted to README.rst for correct formatting on PyPI

### ISSUE THREAD

**Issue by hjacobs** [zalando/pg_view#23]
PyPI uses ReStructured Text, so we should use it in the README too.

Right now the "long description" looks broken (Markdown): https://pypi.python.org/pypi/pg-view

**Comment by hjacobs** [comment]
AFAIK @alexeyklyukin is already working on it :-)

**Comment by alexeyklyukin** [comment]
Done at https://github.com/zalando/pg_view/commit/527eeb387db00107665a7506dafc35af81293fc5

**Comment by hjacobs** [comment]
The long description rendering is still broken for the current package: https://pypi.python.org/pypi/pg-view
I would close this issue only after the PyPI display is correct :smirk:

**Comment by alexeyklyukin** [comment]
Of course it is, since nothing new was pushed to pypi :-) I think I need you to add me to the list of package owners, so I can release the new version.

**Comment by hjacobs** [comment]
@alexeyklyukin sure, what's your PyPI username?

**Comment by alexeyklyukin** [comment]
okliukin

**Comment by hjacobs** [comment]
@alexeyklyukin you are now "owner" of the `pg-view` package: https://pypi.python.org/pypi?:action=role_form&package_name=pg-view
